services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - "3210:3210"
    environment:
      - OPENAI_PROXY_URL=https://api.openai.com/v1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_PROXY_URL=https://api.anthropic.com
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OLLAMA_PROXY_URL=http://host.docker.internal:11434
      - ACCESS_CODE=lobe66
